CREATE TABLE Item (
	id INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	Ref VARCHAR(255) NOT NULL,
	IMG_PATH VARCHAR(255),
	Quantity INTEGER NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE borrowing (
	id INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	User_ID INTEGER NOT NULL,
	Item_id INTEGER NOT NULL,
	Quantity INTEGER NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(id),
	FOREIGN KEY(Item_id) REFERENCES Item(id) ON UPDATE NO ACTION ON DELETE CASCADE
);

